### PR TITLE
[Bugfix] Selector Menu Not Visibile On Line Items Table

### LINKED ISSUE #2307: Dropdown Custom Field in Product - Listentries are hide behind the Add Item-Entry
## Setup
- Version: v5.11.23
- Environment: Docker

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo?
YES
- Have you searched existing issues?
YES

## Describe the bug
I create a custom-Field for Product with type "Dropdown".
Wenn create a new invoice or Quote the Fielld is listed, but the dropdown-list is hided behind the Banner with the "+ Add Item" Entry

### Steps To Reproduce
Create a new Custom-Field for product, Select Dropdown Type, add a few List-Entrys, create a new quote or invoice.

### Expected Behavior
Seeing the complete list of entrys in the Dropdown-List

### Screenshots
error_dropdown_list

### PR DESCRIPTION
**Pull request by Civolilah**
@beganovich @turbo124 The PR includes a fix for the selector menu not being visible in the line items table. Screenshot:

Screenshot 2025-01-15 at 23 00 49

Closes #2307 

Let me know your thoughts.

### CODE REVIEW

File: src/components/CustomField.tsx [hunk 1]
```diff
@@ -20,6 +20,7 @@ import { Entity } from '$app/common/hooks/useEntityCustomFields';
 interface Props extends InputCustomFieldProps {
   fieldOnly?: boolean;
   noExternalPadding?: boolean;
+  selectMenuPosition?: 'fixed' | 'absolute';
```
Comment (beganovich) [inline src/components/CustomField.tsx:23]: What are the differences here? From what I can see, we always use “fixed”. Is absolute old default?

**Review by beganovich — APPROVED** [review]

File: src/components/CustomField.tsx (hunk 1 above)
Comment (Civolilah) [reply src/components/CustomField.tsx:23]: @beganovich Actually, we don't set anything by default - the `menuPosition` component prop is left to use the package's default setting. It accepts 'fixed' and 'absolute' values. While we NEVER use 'absolute', I initially included it since the package accepts that value. However, to avoid confusion, I've removed 'absolute' and kept only 'fixed'.

**Review by beganovich — APPROVED** [review]
